// Tabla de iconos: nombre propio → icono de Lucide. `npm run icons` genera public/icons.svg (sprite) a partir de ella
// y actualiza la versión de SPRITE. Los nombres propios se conservan para no tocar las pantallas que los usan.
export const ICON_NAMES = {
  today: "CalendarCheck",
  leads: "Users",
  funnel: "Filter",
  channels: "Radio",
  workflows: "Workflow",
  settings: "Settings",
  bell: "Bell",
  report: "BarChart3",
  duplicate: "Copy",
  team: "Users",
  user: "UserRound",
  history: "History",
  folder: "Folder",
  grid: "LayoutGrid",
  list: "List",
  link: "Link2",
  plus: "Plus",
  logout: "LogOut",
  phone: "Phone",
  whatsapp: "MessageCircle",
  mail: "Mail",
  chevron: "ChevronRight",
  close: "X",
  menu: "Menu",
  sidebar: "PanelLeft",
  alert: "AlertTriangle",
  more: "Ellipsis",
  chevronDown: "ChevronDown",
  external: "ExternalLink",
  wallet: "Wallet",
  calendar: "CalendarClock",
  tasks: "ClipboardList",
  search: "Search",
  stageSettings: "Settings2",
  expand: "ChevronsLeftRight",
  owner: "UserRoundCheck",
  sort: "ArrowUpDown",
  check: "Check",
  download: "Download",
  upload: "Upload",
  eye: "Eye",
  info: "Info",
  trendUp: "TrendingUp",
  trendDown: "TrendingDown",
  columns: "Columns3",
  table: "Table2",
  sliders: "SlidersHorizontal",
  date: "Calendar",
  tag: "Tag",
  clock: "Clock",
  won: "CircleCheck",
  lost: "CircleX",
  circle: "Circle",
  grip: "GripVertical",
  trash: "Trash",
  edit: "Pencil",
  save: "Save",
  bookmark: "Bookmark",
  filters: "ListFilter",
  scale: "Scale",
  court: "Landmark",
} as const;

export type IconName = keyof typeof ICON_NAMES;

/** Ruta del sprite con su versión (la actualiza `npm run icons`); se sirve con caché inmutable desde next.config. */
export const SPRITE = "/icons.svg?v=457e8bab";
